export const SET_POKEMON_LIST = 'SET_POKEMON_LIST';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
